platform :ios, '16.0'
project 'HealthTimeline.xcodeproj'

target 'HealthTimeline' do
  use_frameworks!
  pod 'SQLCipher', '~> 4.6'

  target 'HealthTimelineTests' do
    inherit! :search_paths
  end
end
